### ISSUE TITLE
[Material]the "Outlined" family of styles need to be reviewed for focused border handling

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/Uno.Themes#1500]
## Current behavior

Here is a demonstration of the issue for PasswordBox (#1493) that had been addressed:
![material outlined passbox on hover](https://github.com/user-attachments/assets/9b957b6c-7936-4f9d-9af0-381b39eb7227)
![material outlined passbox on hover](https://github.com/user-attachments/assets/36725575-2765-48d4-9fec-1aa89267a1c0)

That said, we still have similar problem within the "Outlined" family of styles for controls that can receive input-focused:
> the list is comprehensive.
- [x] ~~ComboBox~~ (fixed in #1502) 
- [x] ~~TextBox~~ (fixed in #1494)
- [x] ~~PasswordBox~~ (fixed in #1497)

## Expected behavior
^ should not happen
